name: Python test

on:
  push:
    branches:
      - main
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3.10 -m pip install --upgrade pip
          pip3 install -e .

      - name: Run unit tests
        run: |
          python3.10 -m unittest discover -s tests
